name: Build Gatsby site
on:
  push:
    branches: ['develop']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build env file
        run: |
          touch .env.production
          echo CONTENTFUL_SPACE_ID =${{ secrets.CONTENTFUL_SPACE_ID }} >> .env.production \
          echo CONTENTFUL_ACCESS_TOKEN = ${{ secrets.CONTENTFUL_ACCESS_TOKEN }} >> .env.production
      - name: Build production site
        run: npm run build
